### ISSUE TITLE
fomatting issue for prec=0 in angles.fmt_angle(dec, pre=0, trunc=True)

### ISSUE THREAD

**Issue by richardgmcmahon** [phn/angles#1]
> > > dec=1.99999
> > > 
> > > print angles.fmt_angle(dec, pre=1, trunc=True)
> > > +01 59 59.9
> > > 
> > > print angles.fmt_angle(dec, pre=0, trunc=True)
> > > +01 59 059

should be 01 59 59

**Comment by phn** [comment]
Hello,

Thank you very much for reporting this error, and please accept my sincere apologizes for taking this long to address this issue.

Regards,
Prasanth
